// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnygbflquamrzogusuyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJueWdiZmxxdWFtcnpvZ3VzdXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTg3NTAsImV4cCI6MjA1NTk5NDc1MH0.6g-5sx8RoFhr-holqOIYkLhwYrGbeWqhTAc0tBen-N4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);